### ISSUE TITLE
ValueError: The glob ganfit_plus/subject_01/Model/frontal1/obj/*.obj yields no assets

### ISSUE THREAD

**Issue by nicolast0604** [barisgecer/GANFit#19]
python3 micc_evaluation.py --template template.obj --template_lms landmark_ids.pkl ganfit_plus ganfit_reocnstruction

/home/nicolast0604/GANFit/env/lib/python3.6/site-packages/menpo/image/base.py:25: UserWarning: Falling back to scipy interpolation for affine warps
  warn("Falling back to scipy interpolation for affine warps")
ID: 1
Traceback (most recent call last):
  File "micc_evaluation.py", line 100, in <module>
    distances = benchmarker.benchmark(args.reconstruction_path)
  File "micc_evaluation.py", line 83, in benchmark
    distances[setting_id, scan-1, id-1] = self.calculate_error(fitting_path, gt_path, id, setting, scan, False)
  File "micc_evaluation.py", line 56, in calculate_error
    org = m3io.import_meshes(self.registration_path + gt_path + 'obj/*.obj')[0]
  File "/home/nicolast0604/GANFit/env/lib/python3.6/site-packages/menpo3d/io/input/base.py", line 185, in import_meshes
    verbose=verbose,
  File "/home/nicolast0604/GANFit/env/lib/python3.6/site-packages/menpo/io/input/base.py", line 880, in _import_glob_lazy_list
    raise ValueError("The glob {} yields no assets".format(pattern))
ValueError: The glob ganfit_plus/subject_01/Model/frontal1/obj/*.obj yields no assets

**Comment by barisgecer** [comment]
It seems glob cannot find ganfit_plus reconstructions.
Did you download it from the link provided in readme? (https://drive.google.com/file/d/1o5O0okEy-KH6WSkTycYp5OWEqJa3KQfX/view)
